# Please DO NOT set the following properties `sonar.organization` and `sonar.projectKey` in this file. They must be stored as `SONAR_ORGANISATION_KEY` and `SONAR_PROJECT_KEY` GitHub secrets.

sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.sources=packages
sonar.tests=packages, tests/
sonar.test.inclusions=packages/**/__tests__/**/*, tests/**/*
sonar.exclusions=packages/**/__tests__/**/*
sonar.terraform.provider.aws.version=5.54.1
sonar.cpd.exclusions=**.test.*
sonar.coverage.exclusions=tests/**/*, **/*.dev.*, packages/**/__tests__/**/*, **/jest.config.ts, **/jest.config.js, scripts/**/*

#sonar.python.coverage.reportPaths=.coverage/coverage.xml
sonar.javascript.lcov.reportPaths=lcov.info
